apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omniflow
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - app.example.com
      secretName: omniflow-tls
