/**
 * The built-in plugin catalog, seeded on boot (same pattern as
 * PermissionsService). A "plugin" here covers two kinds of installable
 * unit that turn out to have the exact same shape — a catalog entry plus
 * per-company install/enable state:
 *
 * - MODULE: one of the 20 core business modules. These are what the
 *   sidebar is generated from (apps/web/src/components/sidebar.tsx calls
 *   GET /plugins/nav), instead of a hard-coded nav array — a company only
 *   sees a module if it's installed for that company AND the current user
 *   holds `<permissionModule>:read`.
 * - INTEGRATION: a lightweight third-party hook (Slack, Zapier, a custom
 *   webhook) the event bridge (plugin-event-bridge.service.ts) checks
 *   before reacting to a domain event for a given company. Real
 *   integrations register themselves the same way — add a catalog entry
 *   and a branch in the event bridge.
 */
export interface PluginDefinition {
  key: string;
  kind: "MODULE" | "INTEGRATION";
  name: string;
  description: string;
  version: string;
  author?: string;
  icon?: string;
  route?: string;
  permissionModule?: string;
  sortOrder?: number;
}

export const PLUGIN_CATALOG: PluginDefinition[] = [
  {
    key: "webhook-notifier",
    kind: "INTEGRATION",
    name: "Webhook Notifier",
    description:
      "POSTs a JSON payload to a configured URL whenever a notification is created for this company " +
      "(new user welcomed, role granted, etc.) — the generic integration point for Slack, Zapier, or a custom listener.",
    version: "0.1.0",
    author: "Omniflow",
  },
  {
    key: "dashboard",
    kind: "MODULE",
    name: "Dashboard",
    description: "Company-wide activity and stats.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "LayoutDashboard",
    route: "/dashboard",
    sortOrder: 0,
  },
  {
    key: "crm",
    kind: "MODULE",
    name: "CRM",
    description: "Accounts, contacts, leads, and deals.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "Users2",
    route: "/crm",
    permissionModule: "crm",
    sortOrder: 1,
  },
  {
    key: "sales",
    kind: "MODULE",
    name: "Sales",
    description: "Products, quotes, sales orders, and invoices.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "ShoppingCart",
    route: "/sales",
    permissionModule: "sales",
    sortOrder: 2,
  },
  {
    key: "inventory",
    kind: "MODULE",
    name: "Inventory",
    description: "Warehouses, stock levels, and stock movements.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "Boxes",
    route: "/inventory",
    permissionModule: "inventory",
    sortOrder: 3,
  },
  {
    key: "accounting",
    kind: "MODULE",
    name: "Accounting",
    description: "Chart of accounts, journal entries, and payments.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "Banknote",
    route: "/accounting",
    permissionModule: "accounting",
    sortOrder: 4,
  },
  {
    key: "hr",
    kind: "MODULE",
    name: "HR",
    description: "Departments, employees, and leave requests.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "UsersRound",
    route: "/hr",
    permissionModule: "hr",
    sortOrder: 5,
  },
  {
    key: "projects",
    kind: "MODULE",
    name: "Projects",
    description: "Projects, tasks, and time entries.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "FolderKanban",
    route: "/projects",
    permissionModule: "projects",
    sortOrder: 6,
  },
  {
    key: "support",
    kind: "MODULE",
    name: "Support",
    description: "Customer support tickets.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "LifeBuoy",
    route: "/support",
    permissionModule: "support",
    sortOrder: 7,
  },
  {
    key: "purchase",
    kind: "MODULE",
    name: "Purchase",
    description: "Suppliers, purchase orders, and goods receipts.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "ShoppingBag",
    route: "/purchase",
    permissionModule: "purchase",
    sortOrder: 8,
  },
  {
    key: "payroll",
    kind: "MODULE",
    name: "Payroll",
    description: "Salary components, pay runs, and payslips.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "Wallet",
    route: "/payroll",
    permissionModule: "payroll",
    sortOrder: 9,
  },
  {
    key: "expenses",
    kind: "MODULE",
    name: "Expenses",
    description: "Expense claims and approval workflow.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "Receipt",
    route: "/expenses",
    permissionModule: "expenses",
    sortOrder: 10,
  },
  {
    key: "assets",
    kind: "MODULE",
    name: "Assets",
    description: "Fixed assets, depreciation, and disposal.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "Building2",
    route: "/assets",
    permissionModule: "assets",
    sortOrder: 11,
  },
  {
    key: "recruitment",
    kind: "MODULE",
    name: "Recruitment",
    description: "Job postings, candidates, applications, and interviews.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "UserSearch",
    route: "/recruitment",
    permissionModule: "recruitment",
    sortOrder: 12,
  },
  {
    key: "contracts",
    kind: "MODULE",
    name: "Contracts",
    description: "Contract lifecycle: activate, terminate, renew.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "FileSignature",
    route: "/contracts",
    permissionModule: "contracts",
    sortOrder: 13,
  },
  {
    key: "manufacturing",
    kind: "MODULE",
    name: "Manufacturing",
    description: "Bills of material and work orders.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "Wrench",
    route: "/manufacturing",
    permissionModule: "manufacturing",
    sortOrder: 14,
  },
  {
    key: "pos",
    kind: "MODULE",
    name: "Point of Sale",
    description: "Register sessions and point-of-sale transactions.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "Store",
    route: "/pos",
    permissionModule: "pos",
    sortOrder: 15,
  },
  {
    key: "attendance",
    kind: "MODULE",
    name: "Attendance",
    description: "Clock-in/out and attendance tracking.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "CalendarCheck",
    route: "/attendance",
    permissionModule: "attendance",
    sortOrder: 16,
  },
  {
    key: "fleet",
    kind: "MODULE",
    name: "Fleet Management",
    description: "Vehicles, trips, and maintenance records.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "Truck",
    route: "/fleet",
    permissionModule: "fleet",
    sortOrder: 17,
  },
  {
    key: "logistics",
    kind: "MODULE",
    name: "Logistics",
    description: "Shipments and delivery tracking.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "PackageCheck",
    route: "/logistics",
    permissionModule: "logistics",
    sortOrder: 18,
  },
  {
    key: "documents",
    kind: "MODULE",
    name: "Documents",
    description: "Document management: folders, versions, check-out locking.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "FileStack",
    route: "/documents",
    permissionModule: "documents",
    sortOrder: 19,
  },
  {
    key: "billing",
    kind: "MODULE",
    name: "Subscription Billing",
    description: "Plans, subscriptions, and recurring invoicing.",
    version: "1.0.0",
    author: "Omniflow",
    icon: "CreditCard",
    route: "/billing",
    permissionModule: "billing",
    sortOrder: 20,
  },
];
