// Central registry of permission keys used for RBAC checks and seeding.
export const PERMISSIONS = {
  // Documents
  DOCUMENT_CREATE: 'document:create',
  DOCUMENT_READ: 'document:read',
  DOCUMENT_UPDATE: 'document:update',
  DOCUMENT_DELETE: 'document:delete',
  DOCUMENT_RESTORE: 'document:restore',
  DOCUMENT_SHARE: 'document:share',
  DOCUMENT_DOWNLOAD: 'document:download',

  // Folders
  FOLDER_CREATE: 'folder:create',
  FOLDER_DELETE: 'folder:delete',

  // Workflow
  WORKFLOW_MANAGE: 'workflow:manage',
  WORKFLOW_APPROVE: 'workflow:approve',
  WORKFLOW_INITIATE: 'workflow:initiate',

  // Signatures
  SIGNATURE_REQUEST: 'signature:request',
  SIGNATURE_SIGN: 'signature:sign',

  // Admin
  ADMIN_USERS: 'admin:users',
  ADMIN_ROLES: 'admin:roles',
  ADMIN_DEPARTMENTS: 'admin:departments',
  ADMIN_ORG_SETTINGS: 'admin:org_settings',

  // Audit / Reports
  AUDIT_VIEW: 'audit:view',
  REPORTS_VIEW: 'reports:view',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'Super Admin',
  ADMIN: 'Admin',
  MANAGER: 'Manager',
  EMPLOYEE: 'Employee',
  AUDITOR: 'Auditor',
} as const;

export const ROLE_PERMISSION_MAP: Record<string, PermissionKey[]> = {
  [SYSTEM_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [SYSTEM_ROLES.ADMIN]: [
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_UPDATE,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.DOCUMENT_RESTORE,
    PERMISSIONS.DOCUMENT_SHARE,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.FOLDER_CREATE,
    PERMISSIONS.FOLDER_DELETE,
    PERMISSIONS.WORKFLOW_MANAGE,
    PERMISSIONS.WORKFLOW_APPROVE,
    PERMISSIONS.WORKFLOW_INITIATE,
    PERMISSIONS.SIGNATURE_REQUEST,
    PERMISSIONS.SIGNATURE_SIGN,
    PERMISSIONS.ADMIN_USERS,
    PERMISSIONS.ADMIN_DEPARTMENTS,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [SYSTEM_ROLES.MANAGER]: [
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_UPDATE,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.DOCUMENT_SHARE,
    PERMISSIONS.FOLDER_CREATE,
    PERMISSIONS.WORKFLOW_APPROVE,
    PERMISSIONS.WORKFLOW_INITIATE,
    PERMISSIONS.SIGNATURE_REQUEST,
    PERMISSIONS.SIGNATURE_SIGN,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [SYSTEM_ROLES.EMPLOYEE]: [
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_UPDATE,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.WORKFLOW_INITIATE,
    PERMISSIONS.SIGNATURE_SIGN,
  ],
  [SYSTEM_ROLES.AUDITOR]: [PERMISSIONS.DOCUMENT_READ, PERMISSIONS.AUDIT_VIEW, PERMISSIONS.REPORTS_VIEW],
};
